[package]
name = "gpws"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
bincode = "*"
byteorder = "*"
clap = {version = "*", features = ["derive"]}
hextree = "*"
hyper = {version = "*", features = ["server", "http1", "full"]}
tokio = {version = "*", features = ["full"]}
